church_site/urls.py
from allauth.account.views import confirm_email, email_verification_sent
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers

# from telegram.api.controllers import LiveSubscriptionViewSet

router = routers.DefaultRouter()
# router.register(r'subscription/live', LiveSubscriptionViewSet)
# router.register(r'streams', StreamsViewSet)

urlpatterns = [
    path("", include("core.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include(router.urls)),
    path("api/v1/streams/", include("streams.api.urls")),
    # path('api/v1/telegram/', include('telegram.api_urls')),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path(
        "dj-rest-auth/registration/account-confirm-email/<str:key>/",
        confirm_email,
        name="account_email_verification_sent",
    ),
    path(
        "dj-rest-auth/registration/account-email-verification-sent/",
        email_verification_sent,
        name="account_email_verification_sent",
    ),
    path("dj-rest-auth/", include("dj_rest_auth.urls")),
    path("dj-rest-auth/registration/", include("dj_rest_auth.registration.urls")),
    path("users/", include("accounts.urls")),
    path("bulletin/", include("bulletin.urls")),
    path("churches/", include("churches.urls")),
    path("speakers/", include("speakers.urls")),
    path("schedules/", include("schedules.urls")),
    path("sermons/", include("sermons.urls")),
    path("streams/", include("streams.urls")),
    path("contactus/", include("contactus.urls")),
    path("forms/", include("forms.urls")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core.views import HomeView
from core.views.pages import set_timezone

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('set_timezone/', set_timezone, name='set_timezone')
]

streams/api/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from streams.api.controllers import StreamsList

urlpatterns = [
    path('', StreamsList.as_view()),
]

urlpatterns = format_suffix_patterns(urlpatterns)

streams/urls.py
from django.urls import path

from .views import (StreamsListView, LiveAudioView, LiveVideoView, StreamsAdminListView, StreamsAdminCreateView,
                    StreamAdminUpdateView, StreamAdminLiveUpdateView)

app_name = 'streams'

urlpatterns = [
    path('live/', StreamsListView.as_view(), name='streams-list'),
    path('live/<str:church>/', StreamsListView.as_view(), name='streams-list-filtered'),
    path('live/<str:church>/<int:pk>/audio/', LiveAudioView.as_view(), name='live-audio'),
    path('live/<str:church>/<int:pk>/video/', LiveVideoView.as_view(), name='live-video'),
    path('manage/streams/', StreamsAdminListView.as_view(), name='streams-admin-list'),
    path('manage/streams/add/', StreamsAdminCreateView.as_view(), name='streams-admin-create'),
    path('manage/streams/<int:pk>/update/', StreamAdminUpdateView.as_view(), name='streams-admin-update'),
    path('manage/streams/<int:pk>/live/', StreamAdminLiveUpdateView.as_view(), name='streams-admin-update-live'),
]

streams/models.py
from uuid import uuid4
from os import path

from django.db import models

from speakers.models import Speaker
from schedules.models import Event


class Stream(models.Model):
    event = models.ForeignKey(Event, on_delete=models.PROTECT, related_name='streams')
    title = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(null=True, blank=True)
    speakers = models.ManyToManyField(Speaker, related_name='streams')
    live_url = models.URLField(blank=True, null=True)
    live_mixlr_audio = models.BooleanField(default=False)
    live = models.BooleanField(default=False)
    audio_views = models.IntegerField(default=0)
    video_views = models.IntegerField(default=0)

    class Meta:
        ordering = ('event', 'title')
        unique_together = ('event', 'title')

    def __str__(self):
        return self.title

streams/forms.py
from core.forms import CoreModelForm
from schedules.selectors import get_admin_events
from streams.models import Stream


class StreamCreateForm(CoreModelForm):
    def __init__(self, user, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['event'].queryset = get_admin_events(user=user, order_by_start='asc', current_events_only=True)

    class Meta:
        model = Stream
        fields = ('event', 'title', 'description', 'speakers', 'live_url', 'live_mixlr_audio', 'live')

streams/api/controllers.py
from django.db.models import Q
from django.utils import timezone
from rest_framework import serializers
from rest_framework.response import Response
from rest_framework.views import APIView

from churches.models import Church
from schedules.models import Event
from speakers.models import Speaker
from streams.models import Stream


class StreamsList(APIView):
    def get(self, request):
        class EventSerializer(serializers.ModelSerializer):
            class ChurchSerializer(serializers.ModelSerializer):
                class Meta:
                    model = Church
                    fields = ['name', 'slug']

            class StreamSerializer(serializers.ModelSerializer):
                class SpeakerSerializer(serializers.ModelSerializer):
                    class Meta:
                        model = Speaker
                        fields = ['name']

                speakers = SpeakerSerializer(many=True, read_only=True)

                class Meta:
                    model = Stream
                    fields = ['id', 'title', 'speakers', 'live', 'live_mixlr_audio']

            streams = StreamSerializer(many=True, read_only=True)
            church = ChurchSerializer(read_only=True)

            class Meta:
                model = Event
                fields = ['id', 'title', 'start', 'end', 'church', 'streams']

        queryset = Event.objects.filter(
            (Q(start__gt=timezone.now()) & Q(live_stream=True)) | Q(streams__live=True)
        ).distinct()
        serializer_class = EventSerializer(queryset, many=True)
        return Response(serializer_class.data)

streams/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from core.views.base import (
    AdminListView,
    BaseDetailView,
    BaseCreateView,
    BaseUpdateView,
)
from .forms import StreamCreateForm

from .models import Stream
from .selectors import get_live_streams, get_member_streams


class StreamsListView(View):
    def get(self, request):
        context = {
            "page_title": "Live - Mennoniten Gemeinde",
            "current_page": "live",
        }
        return render(request, "streams/streams-list-apline.html", context)


class LiveAudioView(BaseDetailView):
    # page_title = 'Page Title'
    current_page = "live"
    model = Stream
    template_name = "streams/live-audio.html"
    context_object_name = "stream"
    queryset = get_live_streams()

    def get_context_data(self, **kwargs):
        context = super(LiveAudioView, self).get_context_data(**kwargs)
        context["page_title"] = f"Live Audio - {self.object.title}"
        try:
            context["stream"].audio_views += 1
            context["stream"].save()
        except Exception as e:
            print("Error", e)
        return context

    # def get_queryset(self):
    #     return self.model.objects.filter(live=True)


class LiveVideoView(BaseDetailView):
    page_title = "Page Title"
    current_page = "live"
    model = Stream
    template_name = "streams/live-video.html"
    context_object_name = "stream"
    queryset = get_live_streams()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["page_title"] = f"Live Video - {self.object.title}"
        try:
            context["stream"].video_views += 1
            context["stream"].save()
        except Exception as e:
            print("Error", e)
        return context

    # def get_queryset(self):
    #     return self.model.objects.filter(live=True)


class StreamsAdminListView(PermissionRequiredMixin, AdminListView):
    permission_required = "streams.view_stream"
    model = Stream
    context_object_name = "streams"
    template_name = "streams/streams-admin-list.html"
    page_title = "Streams - Admin"
    current_page = "admin_streams"
    btn_add_href = reverse_lazy("streams:streams-admin-create")
    # paginate_by = 25
    paginate_by = 10

    def get_queryset(self):
        return get_member_streams(self.request.user, True)

    # def get_template_names(self):
    #     if self.request.htmx:
    #         self.template_name = "streams/partials/stream-admin-list-partial.html"
    #     return super().get_template_names()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['pagination_links'] = self.get_pagination_links(context['page_obj'])
        return context


class StreamsAdminCreateView(PermissionRequiredMixin, BaseCreateView):
    permission_required = "streams.add_stream"
    model = Stream
    template_name = "admin-form-view.html"
    form_class = StreamCreateForm
    success_url = reverse_lazy("streams:streams-admin-list")
    page_title = "New Stream - Admin"
    current_page = "admin_streams"
    btn_back_href = reverse_lazy("streams:streams-admin-list")

    def get_queryset(self):
        return get_member_streams(self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class StreamAdminUpdateView(PermissionRequiredMixin, BaseUpdateView):
    permission_required = "streams.change_stream"
    model = Stream
    template_name = "admin-form-view.html"
    form_class = StreamCreateForm
    success_url = reverse_lazy("streams:streams-admin-list")
    page_title = "Update Stream - Admin"
    current_page = "admin_streams"
    btn_back_href = reverse_lazy("streams:streams-admin-list")

    def get_queryset(self):
        return get_member_streams(self.request.user)

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class StreamAdminLiveUpdateView(PermissionRequiredMixin, BaseUpdateView):
    permission_required = "streams.change_stream"
    http_method_names = ["post"]
    model = Stream
    fields = ["live"]
    success_url = reverse_lazy("streams:streams-admin-list")

    def get_queryset(self):
        return get_member_streams(self.request.user)

templates/streams/live-audio.html
{% extends '_layout.html' %}

{% block meta %}
  <meta name="referrer" content="origin-when-cross-origin">
{% endblock %}

{% block content %}

  <div class="px-3 md:px-0">
    <button onclick="window.history.back()" class="btn btn-outline mt-3"><i
        class="fa-solid fa-arrow-left mr-2"></i>Back
    </button>

    <div class="card bg-base-100 mt-3">
      <div class="card-body">
        <h4 class="card-title">{{ stream.title }}</h4>
        <small>{{ stream.event.church }}</small>

        <div class="flex space-x-2 my-3">
          {% for speaker in stream.speakers.all %}
            <div class="badge badge-primary"><i class="fa-solid fa-microphone mr-2"></i>{{ speaker }}</div>
          {% endfor %}
        </div>

        {% if stream.event.church.mixlr_url %}
          <div class="mt-3">
            <iframe src="{{ stream.event.church.mixlr_url }}" frameborder="0" scrolling="no" height="200px" width="100%"></iframe>
          </div>
        {% endif %}
      </div>
    </div>
  </div>

{% endblock %}

templates/streams/live-video.html
{% extends '_layout.html' %}

{% block meta %}
  <meta name="referrer" content="origin-when-cross-origin">
{% endblock %}

{% block content %}

  <div class="px-3 md:px-0 pb-4">
    <a href="{% url 'streams:streams-list' %}" class="btn btn-outline mt-3"><i
        class="fa-solid fa-arrow-left mr-2"></i>Back
    </a>

    <div class="card bg-base-100 mt-3">
      <div class="card-body">

        <iframe class="aspect-video w-full" referrerpolicy="origin-when-cross-origin"
                src="{{ stream.live_url }}"
                allowfullscreen></iframe>

        <h4 class="card-title">{{ stream.title }}</h4>
        <span class="badge badge-secondary">{{ stream.event.church }}</span>

        <div class="flex space-x-2 mb-2">
          {% for speaker in stream.speakers.all %}
            <div class="badge badge-primary"><i
                class="fa-solid fa-microphone mr-2"></i>{{ speaker }}</div>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>

{% endblock %}

templates/streams/streams-admin-list.html
{% extends '_manage_layout.html' %}

{% block tab_content %}
    <div class="px-3 md:px-0 mt-3">

        {% block add_btn %}
            <div class="flex {% if btn_back_href %}justify-between{% else %}justify-end{% endif %} mb-3">
                {% if btn_back_href %}
                    <button class="btn btn-outline" onclick="window.history.back()">
                        <i class="fa-solid fa-arrow-left mr-2"></i>Back
                    </button>
                {% endif %}
                {% if btn_add_href %}
                    <a href="{{ btn_add_href }}" class="btn btn-primary"><i class="fa-solid fa-plus mr-2"></i>Add</a>
                {% endif %}
            </div>
        {% endblock %}

        <div class="card bg-base-100 mb-4">
            <div class="card-body p-4">
                <div id="paginated-content" class="overflow-x-auto">
                    <table x-data id="admin-table" class="table table-compact w-full">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Date</th>
                                <th>Time</th>
                                <th>Speakers</th>
                                {% if user.is_superuser %}
                                    <th>
                                        <i class="fa-solid fa-music"></i>
                                    </th>
                                    <th>
                                        <i class="fa-solid fa-video"></i>
                                    </th>
                                {% endif %}
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody id="tableBody">
                            {% for stream in streams %}
                                <tr>
                                    <td class="align-middle">{{ stream.title }}</td>
                                    <td class="align-middle"
                                        x-text="dayjs(Number({{ stream.event.start|date:'U' }}) * 1000).format('MMM D, YYYY')">
                                    </td>
                                    <td class="align-middle"
                                        x-text="dayjs(Number({{ stream.event.start|date:'U' }}) * 1000).format('h:mm a')">
                                    </td>
                                    <td class="align-middle">
                                        {% for speaker in stream.speakers.all %}
                                            {% if not forloop.first %},{% endif %}
                                            {{ speaker.name }}
                                        {% endfor %}
                                    </td>
                                    {% if user.is_superuser %}
                                        <td class="align-middle">
                                            {% if stream.live_mixlr_audio %}{{ stream.audio_views }}{% endif %}
                                        </td>

                                        <td class="align-middle">{{ stream.video_views }}</td>
                                    {% endif %}
                                    <td class="align-middle flex flex-nowrap space-x-2">
                                        {% if perms.streams.change_stream %}
                                            <form hx-post="{% url 'streams:streams-admin-update-live' pk=stream.id %}"
                                                  hx-select-oob="#main-content">
                                                {% csrf_token %}
                                                <input type="hidden"
                                                       id="id_live"
                                                       name="live"
                                                       value="{% if stream.live %}False{% else %}True{% endif %}">
                                                <button type="submit"
                                                        class="btn btn-sm{% if not stream.live %} btn-outline{% endif %} btn-error flex-nowrap">
                                                    {% if stream.live %}
                                                        <i class="fa-solid fa-circle mr-2"></i>Live
                                                    {% else %}
                                                        Go Live
                                                    {% endif %}
                                                </button>
                                            </form>
                                            <a href="{% url 'streams:streams-admin-update' pk=stream.id %}"
                                               class="btn btn-sm btn-default"><i class="fa-solid fa-edit"></i></a>
                                        {% endif %}
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>

        <div id="paginator">
            {% include "snippets/paginator_snippet.html" %}

        </div>
    </div>

    <div id="table-modal" class="modal modal-bottom sm:modal-middle"></div>
{% endblock %}

templates/streams/streams-list-apline.html
{% extends '_layout.html' %}

{% load static %}

{#{% load compress %}#}

{% block meta %}
    <meta name="robots" content="index, nofollow">{% endblock %}

{% block content %}

    <div class="py-5 px-3">

        <h1 class="text-2xl text-primary font-bold font-serif">Live Streams</h1>
        <hr class="mx-5">

        <div id="live-app" x-data="appLiveStreamComponent" x-init="start" x-cloak>
            <div class="flex justify-center text-white py-4">
                <span class="bg-primary pl-2 pr-5 rounded-lg">I'll look again in:</span>
                <span class="bg-success rounded-lg px-2 -ml-4" x-text="countdown"></span>
            </div>
            <template x-if="liveEvents.length === 0">
                <div class="flex flex-col items-center justify-center">
                    <div>
                        <img :src="liveNotFound[countdownQuote].icon">
                    </div>
                    <div class=" px-4" x-text="liveNotFound[countdownQuote].message"></div>
                </div>
            </template>
            <ul class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 py-4">
                <template x-for="liveEvent in liveEvents">
                    <template x-for="stream in liveEvent.streams" :key="stream.id">
                        <template x-if="stream['live']">
                            <li class="card card-compact bg-base-100 shadow-xl pt-2">
                                <div class="card-body gap-1">
                                    <div class="pb-1">
                                        <h2 class="card-title !mb-0">
                                            <span class="truncate" x-text="stream.title"></span>
                                        </h2>
                                        <p class="badge badge-sm badge-ghost" x-text="liveEvent.church.name"></p>
                                    </div>
                                    <div class="absolute -top-2 right-3">
                                        <span class="badge badge-error">Live</span>
                                    </div>
                                    <div>
                                        <p class="text-sm" x-text="new Date(liveEvent.start).toDateString()"></p>
                                        <p class="text-sm" x-text="getLocalTime(liveEvent.start)"></p>
                                    </div>
                                    <div class="flex py-1 space-x-1">
                                        <template x-for="speaker in stream['speakers']" :key="speaker.name">
                                            <span class="badge badge-primary badge-outline mx-0">
                                                <i class="fa-solid fa-microphone mr-1"></i>
                                                <span x-text="speaker.name"></span>
                                            </span>
                                        </template>
                                    </div>

                                    <div class="card-actions pt-2 justify-between">
                                        <template x-if="stream['live_mixlr_audio']">
                                            <a :href="`/streams/live/${liveEvent.church.slug}/${stream.id}/audio/`"
                                               class="btn w-[45%] space-x-1">
                                                <i class="fa-solid fa-music"></i>Live Audio
                                            </a>
                                        </template>
                                        <a :href="`/streams/live/${liveEvent.church.slug}/${stream.id}/video/`"
                                           class="btn space-x-1"
                                           :class="{'w-full': !stream['live_mixlr_audio'], 'w-[45%]': stream['live_mixlr_audio']}">
                                            <i class="fa-solid fa-video"></i>Live Video
                                        </a>
                                    </div>
                                </div>
                            </li>

                        </template>
                    </template>
                </template>
            </ul>

            <h2 class="mt-10 text-2xl text-primary font-bold font-serif">Scheduled Live Streams</h2>
            <hr class="mb-3 mx-5">

            <ul class="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8 py-4">
                <template x-for="schedule in scheduledEvents" :key="schedule.id">
                    <li class="bg-white rounded-lg shadow divide-y relative">
                        <div class="pt-5 pb-2 px-4">
                            <h3 class="text-lg font-semibold truncate" x-text="schedule.title"></h3>
                            <div class="absolute -top-2 right-3">
                                    <span class="flex-shrink-0 inline-block px-2 py-0.5 text-cyan-50 text-xs font-medium bg-secondary rounded-full"
                                          x-text="schedule.church.name"></span>
                            </div>
                        </div>

                        <div class="py-3 px-4">
                            <p class="text-sm" x-text="new Date(schedule.start).toDateString()"></p>
                            <p class="text-sm" x-text="getLocalTime(schedule.start)"></p>
                        </div>

                    </li>
                </template>
            </ul>

        </div>

    </div>
{% endblock %}

{% block js %}

    <script>
        document.addEventListener('alpine:init', () => {
            Alpine.data('appLiveStreamComponent', () => ({
                countdown: 10,
                countdownQuote: 0,
                liveEvents: [],
                scheduledEvents: [],
                liveNotFound: [
                    {
                        icon: '/static/img/human-2412988_200.png',
                        message: 'I don’t see any streams live at the moment, but don’t worry I will keep looking'
                    },
                    {
                        icon: '/static/img/human-2412988_200.png',
                        message: 'Go grab yourself a coffee it might take another minute'
                    },
                    {
                        icon: '/static/img/human-2412988_200.png',
                        message: 'I’m not sure if I’m seeing any streams live, but I’ll keep looking'
                    },
                    {
                        icon: '/static/img/human-2412988_200.png',
                        message: 'Trust me, you don’t want to miss this'
                    },
                    {
                        icon: '/static/img/human-2412988_200.png',
                        message: 'Hang in there'
                    },
                    {
                        icon: '/static/img/human-2412988_200.png',
                        message: 'The secret of patience is to drink a coffee in the meantime'
                    },
                    {
                        icon: '/static/img/human-2412988_200.png',
                        message: 'Great things take time'
                    }
                ],
                getEvents() {
                    fetch("/api/v1/streams")
                        .then(response => response.json())
                        .then(data => {
                            const tempScheduledEvents = [];
                            const tempLiveEvents = [];
                            for (const event of data) {
                                let hasLive = false;
                                for (const stream of event.streams) {
                                    if (stream['live'] === true) {
                                        hasLive = true;
                                    }
                                }
                                if (hasLive === true) {
                                    tempLiveEvents.push(event);
                                } else {
                                    tempScheduledEvents.push(event);
                                }
                            }
                            this.liveEvents = tempLiveEvents;
                            this.scheduledEvents = tempScheduledEvents;
                        });
                },
                start() {
                    this.getEvents();
                    setInterval(() => {
                        if (this.countdown === 0) {
                            this.countdown = 60;
                            this.countdownQuote = Math.floor(Math.random() * 7);
                            this.getEvents();
                        } else {
                            this.countdown -= 1;
                        }
                    }, 1000);
                },
                getLocalTime(date) {
                    const d = new Date(date).toLocaleTimeString();
                    const dAmPm = d.split(' ');
                    const [hours, minutes, seconds] = dAmPm[0].split(':')
                    return `${hours}:${minutes} ${dAmPm[1]}`
                }
            }));
        });
    </script>
{% endblock %}