church_site/urls.py
from allauth.account.views import confirm_email, email_verification_sent
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers

# from telegram.api.controllers import LiveSubscriptionViewSet

router = routers.DefaultRouter()
# router.register(r'subscription/live', LiveSubscriptionViewSet)
# router.register(r'streams', StreamsViewSet)

urlpatterns = [
    path("", include("core.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include(router.urls)),
    path("api/v1/streams/", include("streams.api.urls")),
    # path('api/v1/telegram/', include('telegram.api_urls')),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path(
        "dj-rest-auth/registration/account-confirm-email/<str:key>/",
        confirm_email,
        name="account_email_verification_sent",
    ),
    path(
        "dj-rest-auth/registration/account-email-verification-sent/",
        email_verification_sent,
        name="account_email_verification_sent",
    ),
    path("dj-rest-auth/", include("dj_rest_auth.urls")),
    path("dj-rest-auth/registration/", include("dj_rest_auth.registration.urls")),
    path("users/", include("accounts.urls")),
    path("bulletin/", include("bulletin.urls")),
    path("churches/", include("churches.urls")),
    path("speakers/", include("speakers.urls")),
    path("schedules/", include("schedules.urls")),
    path("sermons/", include("sermons.urls")),
    path("streams/", include("streams.urls")),
    path("contactus/", include("contactus.urls")),
    path("forms/", include("forms.urls")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core.views import HomeView
from core.views.pages import set_timezone

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('set_timezone/', set_timezone, name='set_timezone')
]

forms/urls.py
from django.urls import path

from .views import (FormsDetailView, AdminFormListView, AdminFormCreateView, AdminTranslationListView,
                    AdminTranslationCreateView, AdminFormUpdateView, AdminTranslationUpdateView)

app_name = 'forms'

urlpatterns = [
    path('<str:slug>/', FormsDetailView.as_view(), name='forms-detail'),
    path('manage/forms/', AdminFormListView.as_view(), name='admin-forms-list'),
    path('manage/forms/create/', AdminFormCreateView.as_view(), name='admin-forms-create'),
    path('manage/forms/<str:slug>/', AdminTranslationListView.as_view(), name='admin-forms-detail'),
    path('manage/forms/<str:slug>/update/', AdminFormUpdateView.as_view(), name='admin-forms-update'),
    path('manage/forms/<str:slug>/translations/create/', AdminTranslationCreateView.as_view(),
         name='admin-translation-create'),
    path('manage/forms/<str:slug>/translations/<int:pk>/update/', AdminTranslationUpdateView.as_view(),
         name='admin-translation-update'),
    # path('manage/messages/<int:pk>/read/', AdminReadMessage.as_view(), name='admin-read-message'),
    # path('manage/messages/<int:pk>/delete/', AdminContactMessageDeleteView.as_view(), name='admin-delete-message'),
]

forms/models.py
from django.db import models

LANGUAGES = (
    ('en', 'English'),
    ('es', 'Español'),
    ('de', 'Deutsch'),
)


class Form(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255)
    description = models.TextField(blank=True)
    language = models.CharField(max_length=2, choices=LANGUAGES, default='en')
    embed_url = models.CharField(max_length=255, blank=True)
    is_active = models.BooleanField(default=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)


class Translation(models.Model):
    form = models.ForeignKey(Form, on_delete=models.CASCADE, related_name='translations')
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True)
    language = models.CharField(max_length=2, choices=LANGUAGES, default='en')
    embed_url = models.CharField(max_length=255, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ('name',)
        unique_together = ('form', 'language')

forms/admin.py
from django.contrib import admin

from forms.models import Form, Translation

admin.site.register(Form)
admin.site.register(Translation)

forms/apps.py
from django.apps import AppConfig


class FormsConfig(AppConfig):
    default_auto_field = 'django.db.models.BigAutoField'
    name = 'forms'

forms/forms.py
from django.template.defaultfilters import slugify

from core.forms import CoreModelForm
from forms.models import Form, Translation


class FormCreateForm(CoreModelForm):
    class Meta:
        model = Form
        fields = ['name', 'description', 'language', 'embed_url', 'is_active']

    def save(self, commit=False):
        form = super(FormCreateForm, self).save(commit=False)
        form.slug = slugify(form.name)
        form.save()
        return form


class TranslationCreateForm(CoreModelForm):
    class Meta:
        model = Translation
        fields = ['name', 'description', 'language', 'embed_url']

forms/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import View

from core.views.base import AdminListView, BaseCreateView, BaseUpdateView
from forms.forms import FormCreateForm, TranslationCreateForm
from forms.models import Form, Translation


class FormsDetailView(View):
    model = Form
    template_name = 'forms/forms-detail.html'
    context_object_name = 'form'
    current_page = 'forms'
    current_translation = None
    translation = None

    def get(self, request, *args, **kwargs):
        form = self.model.objects.filter(slug=kwargs['slug']).first()
        if form:
            if not form.is_active:
                context = {
                    'page_title': f'{form.name} form',
                    'current_page': self.current_page,
                    'form': form,
                }
                if request.htmx:
                    return render(request, 'forms/partials/form-inactive-partial.html', context)
                return render(request, 'forms/form_inactive.html', context)

            if request.GET.get('lang'):
                if request.GET.get('lang') == form.language:
                    self.translation = None
                else:
                    self.translation = form.translations.filter(language=request.GET.get('lang')).first()
                self.current_translation = request.GET.get('lang')

            context = {
                'form': form,
                'translation': self.translation,
                'current_translation': self.current_translation,
                'page_title': f'{form.name} form',
                'current_page': self.current_page,
            }

            if request.htmx:
                return render(request, 'forms/partials/form-card-body-partial.html', context)

            return render(request, self.template_name, context)

        if request.htmx:
            return render(request, 'forms/partials/404-partial.html')
        return render(request, 'forms/404-form.html', {})


class AdminFormListView(PermissionRequiredMixin, AdminListView):
    permission_required = 'forms.view_forms'
    template_name = 'forms/admin-forms-list.html'
    model = Form
    context_object_name = 'forms'
    queryset = Form.objects.all()
    ordering = ['-created_at']
    page_title = 'Forms - Admin'
    current_page = 'admin_forms'
    btn_add_href = reverse_lazy('forms:admin-forms-create')


class AdminFormCreateView(PermissionRequiredMixin, BaseCreateView):
    permission_required = 'forms.add_forms'
    model = Form
    template_name = 'admin-form-view.html'
    form_class = FormCreateForm
    page_title = 'New Form - Admin'
    current_page = 'admin_forms'
    btn_back_href = reverse_lazy('forms:admin-forms-list')
    success_url = reverse_lazy('forms:admin-forms-list')


class AdminFormUpdateView(PermissionRequiredMixin, BaseUpdateView):
    permission_required = 'forms.change_forms'
    model = Form
    template_name = 'admin-form-view.html'
    form_class = FormCreateForm
    page_title = 'Update Form - Admin'
    current_page = 'admin_forms'
    btn_back_href = reverse_lazy('forms:admin-forms-list')
    success_url = reverse_lazy('forms:admin-forms-list')


class AdminTranslationListView(PermissionRequiredMixin, AdminListView):
    permission_required = 'forms.view_translation'
    template_name = 'forms/admin-translations-list.html'
    model = Translation
    context_object_name = 'translations'
    ordering = ['-created_at']
    btn_back_href = reverse_lazy('forms:admin-forms-list')
    page_title = 'Translations - Admin'
    current_page = 'admin_forms'

    def get_queryset(self):
        return Translation.objects.filter(form__slug=self.kwargs['slug'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = Form.objects.filter(slug=self.kwargs['slug']).first()
        context['btn_add_href'] = reverse_lazy('forms:admin-translation-create', kwargs={'slug': self.kwargs['slug']})
        return context


class AdminTranslationCreateView(PermissionRequiredMixin, BaseCreateView):
    permission_required = 'forms.add_translation'
    model = Translation
    template_name = 'admin-form-view.html'
    form_class = TranslationCreateForm
    page_title = 'New Translation - Admin'
    current_page = 'admin_forms'
    btn_back_href = reverse_lazy('forms:admin-forms-list')

    def get_success_url(self):
        return reverse_lazy('forms:admin-forms-detail', kwargs={'slug': self.kwargs['slug']})

    def form_valid(self, form):
        form.instance.form = Form.objects.filter(slug=self.kwargs['slug']).first()
        return super().form_valid(form)


class AdminTranslationUpdateView(PermissionRequiredMixin, BaseUpdateView):
    permission_required = 'forms.change_translation'
    model = Translation
    template_name = 'admin-form-view.html'
    form_class = TranslationCreateForm
    page_title = 'Update Translation - Admin'
    current_page = 'admin_forms'

    def get_success_url(self):
        return reverse_lazy('forms:admin-forms-detail', kwargs={'slug': self.kwargs['slug']})

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['btn_back_href'] = reverse_lazy('forms:admin-forms-detail', kwargs={'slug': self.kwargs['slug']})
        return context

templates/forms/404-form.html
{% extends '_layout.html' %}

{% block content %}
    <div class="h-full px-3 md:px-0 py-5">
        <div class="card bg-base-100 h-full">
            <div id="formContainer" class="card-body gap-0 px-3 md:px-8 justify-center items-center h-full">
                {% include 'forms/partials/404-partial.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/forms/admin-forms-list.html
{% extends 'admin-list-layout.html' %}

{% block add_btn %}

  {% if perms.forms.add_forms %}
    {{ block.super }}
  {% endif %}

{% endblock %}

{% block table_head %}
  <tr>
    <th>Name</th>
    <th>Language</th>
    <th>Active</th>
    <th>Actions</th>
  </tr>
{% endblock %}

{% block table_body %}
  {% for f in forms %}
    <tr>
      <td class="align-middle">{{ f.name }}</td>
      <td class="align-middle">{{ f.language }}</td>
      <td class="align-middle">{{ f.is_active }}</td>
      <td>
        <a href="{% url 'forms:admin-forms-detail' slug=f.slug %}" class="btn btn-outline btn-primary btn-sm">
          <i class="fa fa-eye"></i>
        </a>
        {% if perms.forms.change_form %}
          <a href="{% url 'forms:admin-forms-update' slug=f.slug %}"
             class="btn btn-sm btn-secondary"><i class="fa-solid fa-edit"></i></a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
{% endblock %}

templates/forms/admin-translations-list.html
{% extends 'admin-list-layout.html' %}

{% block add_btn %}

  {% if perms.forms.add_translations %}
    {{ block.super }}
  {% endif %}

{% endblock %}

{% block card_content %}
  <h1 class="card-title">{{ form.name }}</h1>
  <p>{% if request.is_secure %}https://{% else %}
    http://{% endif %}{{ request.get_host }}{% url 'forms:forms-detail' slug=form.slug %}</p>
{% endblock %}

{% block table_head %}
  <tr>
    <th>Name</th>
    <th>Language</th>
    <th>Actions</th>
  </tr>
{% endblock %}

{% block table_body %}
  {% for translation in translations %}
    <tr>
      <td class="align-middle">{{ translation.name }}</td>
      <td class="align-middle">{{ translation.language }}</td>
      <td>
        {% if perms.forms.change_translation %}
          <a href="{% url 'forms:admin-translation-update' slug=form.slug pk=translation.id %}"
             class="btn btn-sm btn-secondary"><i class="fa-solid fa-edit"></i></a>
        {% endif %}
      </td>
    </tr>
  {% endfor %}
{% endblock %}

templates/forms/form_inactive.html
{% extends '_layout.html' %}

{% block content %}
    <div class="h-full px-3 md:px-0 py-5">
        <div class="card bg-base-100 h-full">
            <div id="formContainer" class="card-body gap-0 px-3 md:px-8 justify-center items-center h-full">
                {% include 'forms/partials/form-inactive-partial.html' %}
            </div>
        </div>
    </div>
{% endblock %}

templates/forms/forms-detail.html
{% extends '_layout.html' %}

{% block content %}
    <div class="h-full px-3 md:px-0 py-5">
        <div class="card bg-base-100 h-full">
            <div id="formContainer" class="card-body gap-0 px-3 md:px-8 items-center h-full">
                {% include 'forms/partials/form-card-body-partial.html' %}
            </div>
        </div>
    </div>
{% endblock %}