church_site/urls.py
from allauth.account.views import confirm_email, email_verification_sent
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers

# from telegram.api.controllers import LiveSubscriptionViewSet

router = routers.DefaultRouter()
# router.register(r'subscription/live', LiveSubscriptionViewSet)
# router.register(r'streams', StreamsViewSet)

urlpatterns = [
    path("", include("core.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include(router.urls)),
    path("api/v1/streams/", include("streams.api.urls")),
    # path('api/v1/telegram/', include('telegram.api_urls')),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path(
        "dj-rest-auth/registration/account-confirm-email/<str:key>/",
        confirm_email,
        name="account_email_verification_sent",
    ),
    path(
        "dj-rest-auth/registration/account-email-verification-sent/",
        email_verification_sent,
        name="account_email_verification_sent",
    ),
    path("dj-rest-auth/", include("dj_rest_auth.urls")),
    path("dj-rest-auth/registration/", include("dj_rest_auth.registration.urls")),
    path("users/", include("accounts.urls")),
    path("bulletin/", include("bulletin.urls")),
    path("churches/", include("churches.urls")),
    path("speakers/", include("speakers.urls")),
    path("schedules/", include("schedules.urls")),
    path("sermons/", include("sermons.urls")),
    path("streams/", include("streams.urls")),
    path("contactus/", include("contactus.urls")),
    path("forms/", include("forms.urls")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path

from core.views import HomeView
from core.views.pages import set_timezone

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('set_timezone/', set_timezone, name='set_timezone')
]

home/urls.py
from django.urls import path

from home.views import HomeView

app_name = 'home'

urlpatterns = [
    path('', HomeView.as_view(), name='home')
]

schedules/urls.py
from django.urls import path

from .views import (
    EventsAdminDetailView,
    AttendantCreateView,
    AttendantAdminDetailView,
    AttendantAdminDeleteView,
    AttendantAdminUpdateView,
    AttendantAdminSignupToggle,
    EventsAdminListView,
    EventsAdminAllListView,
    EventsAdminCreateView,
    EventsAdminUpdateView,
    EventsAdminDeleteView,
    EventsView,
    EventTemplateAdminListView,
    EventTemplateAdminCreateView,
    EventTemplateAdminUpdateView,
    EventTemplateAdminDeleteView,
)

app_name = 'schedules'

urlpatterns = [
    path('', EventsView.as_view(), name='events-list'),
    path('<str:church>/', EventsView.as_view(), name='events-list-filtered'),
    path('<str:church>/<int:event>/attendants/add', AttendantCreateView.as_view(), name='attendants-create'),
    path('manage/events/', EventsAdminListView.as_view(), name='events-admin-list'),
    path('manage/events/all/', EventsAdminAllListView.as_view(), name='events-admin-all-list'),
    path('manage/events/add/', EventsAdminCreateView.as_view(), name='events-admin-create'),
    path('manage/events/<int:pk>/update/', EventsAdminUpdateView.as_view(), name='events-admin-update'),
    path('manage/events/<int:pk>/', EventsAdminDetailView.as_view(), name='events-admin-detail'),
    path('manage/events/<int:pk>/delete', EventsAdminDeleteView.as_view(), name='events-admin-delete'),
    path('manage/events/<int:event>/attendants/<int:pk>/', AttendantAdminDetailView.as_view(),
         name='attendants-admin-detail'),
    path('manage/events/<int:event>/attendants/<int:pk>/update/', AttendantAdminUpdateView.as_view(),
         name='attendants-admin-update'),
    path('manage/events/<int:event>/attendants/<int:pk>/delete/', AttendantAdminDeleteView.as_view(),
         name='attendants-admin-delete'),
    path('manage/events/<int:pk>/attendants/signup/toggle/', AttendantAdminSignupToggle.as_view(),
         name='attendants-admin-signup-toggle'),
    path('manage/event-templates/', EventTemplateAdminListView.as_view(), name='event-templates-admin-list'),
    path('manage/event-templates/add/', EventTemplateAdminCreateView.as_view(), name='event-templates-admin-create'),
    path('manage/event-templates/<int:pk>/edit/', EventTemplateAdminUpdateView.as_view(),
         name='event-templates-admin-update'),
    path('manage/event-templates/<int:pk>/delete/', EventTemplateAdminDeleteView.as_view(),
         name='event-templates-admin-delete'),
]

sermons/urls.py
from django.urls import path

from .views import (
    SermonsListView,
    SermonsDetailView,
    SermonsAdminCreateView,
    SermonsAdminListView,
    SermonAdminUpdateView,
    download_sermon
)

app_name = 'sermons'

urlpatterns = [
    path('', SermonsListView.as_view(), name='sermons-list'),
    path('<str:church>/', SermonsListView.as_view(), name='sermons-list-filtered'),
    path('<str:church>/<int:pk>/', SermonsDetailView.as_view(), name='sermons-detail'),
    path('<int:pk>/download', download_sermon, name='sermons-download'),
    path('manage/sermons/', SermonsAdminListView.as_view(), name='sermons-admin-list'),
    path('manage/sermons/add/', SermonsAdminCreateView.as_view(), name='sermons-admin-create'),
    path('manage/sermons/<int:pk>/update/', SermonAdminUpdateView.as_view(), name='sermons-admin-update'),
]

streams/urls.py
from django.urls import path

from .views import (StreamsListView, LiveAudioView, LiveVideoView, StreamsAdminListView, StreamsAdminCreateView,
                    StreamAdminUpdateView, StreamAdminLiveUpdateView)

app_name = 'streams'

urlpatterns = [
    path('live/', StreamsListView.as_view(), name='streams-list'),
    path('live/<str:church>/', StreamsListView.as_view(), name='streams-list-filtered'),
    path('live/<str:church>/<int:pk>/audio/', LiveAudioView.as_view(), name='live-audio'),
    path('live/<str:church>/<int:pk>/video/', LiveVideoView.as_view(), name='live-video'),
    path('manage/streams/', StreamsAdminListView.as_view(), name='streams-admin-list'),
    path('manage/streams/add/', StreamsAdminCreateView.as_view(), name='streams-admin-create'),
    path('manage/streams/<int:pk>/update/', StreamAdminUpdateView.as_view(), name='streams-admin-update'),
    path('manage/streams/<int:pk>/live/', StreamAdminLiveUpdateView.as_view(), name='streams-admin-update-live'),
]

core/models.py
from django.db import models

# Create your models here.

core/forms.py
from django.forms import ModelForm

TEXTAREA_FIELD_TYPES = ("Textarea",)
INPUT_FIELD_TYPES = (
    "TextInput",
    "URLInput",
    "EmailInput",
    "NumberInput",
    "PasswordInput",
    "DateTimeInput",
)
SELECT_FIELD_TYPES = ("Select", "LazySelect", "SelectMultiple")
FILE_WIDGET_TYPES = ("ClearableFileInput", "FileInput")
CHECKBOX_FIELD_TYPES = ("CheckboxInput", "CheckboxSelectMultiple")


class CoreModelForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # for field in self.fields:
        #     print(self.fields[field].widget.__class__.__name__)
        self.style_fields()

    def style_fields(self):
        for field in self.fields:
            style_class = ""
            if self.fields[field].widget.__class__.__name__ in INPUT_FIELD_TYPES:
                style_class = "input input-bordered w-full max-w-xs"
            elif self.fields[field].widget.__class__.__name__ in TEXTAREA_FIELD_TYPES:
                style_class = "textarea textarea-bordered w-full h-20 max-w-xs"
            elif self.fields[field].widget.__class__.__name__ in SELECT_FIELD_TYPES:
                style_class = "select select-bordered w-full max-w-xs"
            elif self.fields[field].widget.__class__.__name__ in FILE_WIDGET_TYPES:
                style_class = "file-input"
            elif self.fields[field].widget.__class__.__name__ in CHECKBOX_FIELD_TYPES:
                style_class = "toggle toggle-primary"
            self.fields[field].widget.attrs.update({"class": style_class})

core/views.py
from django.urls import reverse_lazy
from django.utils import timezone
from django.views import View
from django.views.generic import CreateView

from contactus.forms import ContactUsForm
from schedules.selectors import get_events
from sermons.selectors import get_random_sermons


class CoreView(View):
    template_name: str = None
    current_page: str = None
    btn_back_href: str = None
    btn_add_href: str = None

    def get_template_name(self):
        return self.template_name

    def get_current_page(self):
        return self.current_page

    def get_btn_back_href(self):
        return self.btn_back_href

    def get_btn_add_href(self):
        return self.btn_add_href

    def get_context_data(self, **kwargs):
        context = {
            'template_name': self.get_template_name(),
            'current_page': self.get_current_page(),
            'btn_back_href': self.get_btn_back_href(),
            'btn_add_href': self.get_btn_add_href(),
        }
        return context


class HomeView(CreateView):
    template_name = 'core/home.html'
    form_class = ContactUsForm
    page_title = 'Mennoniten Gemeinde'
    success_url = reverse_lazy('core:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.page_title
        context['current_page'] = 'home'
        events = get_events(limit=5)
        local_timezone = timezone.get_current_timezone()
        for event in events:
            event.start = event.start.astimezone(local_timezone)
        context['events'] = events
        context['sermons'] = get_random_sermons(limit=5)
        return context

    def get_initial(self):
        initial = super(HomeView, self).get_initial()
        initial['page_title'] = self.page_title
        return initial

core/views/base.py
from typing import List

from django.core.paginator import Page
from django.views import View
from django.views.generic import ListView, UpdateView, DetailView, CreateView


class PageProperties:
    page_title: str = None
    current_page: str = None

    def get_page_title(self):
        if not self.page_title:
            raise NotImplementedError('Page title must be set')
        return self.page_title

    def get_current_page(self):
        if not self.current_page:
            raise NotImplementedError('Current page must be set')
        return self.current_page


class FormProperties:
    form_has_files = False


class CoreView(PageProperties, View):
    template_name: str = None
    btn_back_href: str = None
    btn_add_href: str = None

    def get_template_name(self):
        return self.template_name

    def get_btn_back_href(self):
        return self.btn_back_href

    def get_btn_add_href(self):
        return self.btn_add_href

    def get_context_data(self, **kwargs):
        context = {
            'template_name': self.get_template_name(),
            'current_page': self.get_current_page(),
            'btn_back_href': self.get_btn_back_href(),
            'btn_add_href': self.get_btn_add_href(),
        }
        return context


class BaseListView(PageProperties, ListView):

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.page_title
        context['current_page'] = self.current_page
        if context['page_obj']:
            context['pagination_links'] = self.get_pagination_links(context['page_obj'])
        return context

    @staticmethod
    def get_pagination_links(page: Page) -> List[int]:
        """returns pagination links for paginated lists"""
        if page.paginator.num_pages > 5:
            links = []
            for p in page.paginator.page_range:
                if 5 >= p > 3 > page.number:
                    links.append(p)
                elif p > page.paginator.count - 5 and page.number > page.paginator.count - 3:
                    links.append(p)
                elif (page.number + 2) >= p >= (page.number - 2):
                    links.append(p)
            return links
        else:
            return page.paginator.page_range


class BaseCreateView(PageProperties, FormProperties, CreateView):
    btn_back_href = None

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.page_title
        context['current_page'] = self.current_page
        context['btn_back_href'] = self.btn_back_href
        context['form_has_files'] = self.form_has_files
        return context


class BaseDetailView(PageProperties, DetailView):
    btn_back_href = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['btn_back_href'] = self.btn_back_href
        context['page_title'] = self.page_title
        context['current_page'] = self.current_page
        return context


class BaseUpdateView(PageProperties, FormProperties, UpdateView):
    btn_back_href = None

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['page_title'] = self.page_title
        context['current_page'] = self.current_page
        context['btn_back_href'] = self.btn_back_href
        context['form_has_files'] = self.form_has_files
        return context


class AdminListView(BaseListView):
    btn_add_href = None
    btn_back_href = None

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['btn_add_href'] = self.btn_add_href
        context['btn_back_href'] = self.btn_back_href
        return context

core/views/pages.py
import json

from django.conf import settings
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.utils import timezone
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_http_methods

from contactus.forms import ContactUsForm
from core.views.base import BaseCreateView
from schedules.selectors import get_events
from sermons.selectors import get_random_sermons


class HomeView(BaseCreateView):
    template_name = 'core/home.html'
    form_class = ContactUsForm
    page_title = 'Mennoniten Gemeinde'
    current_page = 'home'
    success_url = reverse_lazy('core:home')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        events = get_events(limit=5)
        local_timezone = timezone.get_current_timezone()
        for event in events:
            event.start = event.start.astimezone(local_timezone)
        context['events'] = events
        context['sermons'] = get_random_sermons(limit=5)
        return context

    def get_initial(self):
        initial = super(HomeView, self).get_initial()
        initial['page_title'] = self.page_title
        return initial


@csrf_exempt
@require_http_methods(["POST"])
def set_timezone(request):
    data = json.loads(request.body)
    active_timezone = timezone.get_current_timezone()
    server_timezone = settings.TIME_ZONE
    if active_timezone == data["timezone"]:
        return JsonResponse({"success": True, "redirect": False}, status=200)
    
    request.session["user_timezone"] = data["timezone"]
    if server_timezone == data["timezone"] and active_timezone == data["timezone"]:
        return JsonResponse({"success": True, "reload": False}, status=200)
    return JsonResponse({"success": True, "reload": True}, status=200)

core/templates/core/home.html
{% extends '_layout.html' %}

{% load static %}

{% block meta %}<meta name="robots" content="index, follow" />{% endblock %}

{% block content %}
    <div class="pb-4 sm:pt-4">
        <div class="bg-hero-background flex flex-col items-center justify-center py-14 min-h-[20rem] bg-cover bg-no-repeat bg-center shadow rounded-b-2xl sm:rounded-xl">
            <h1 class="text-3xl text-gray-200 text-center">
                Welcome to <span class="text-primary font-bold font-serif">Mennoniten Gemeinde</span>
            </h1>
            <hr class="text-white w-10/12 my-2">
            <p class="text-white mx-24 text-center">
                For other foundation can no man lay than that is laid, which is
                Jesus
                Christ. 1 Corinthians 3:11
            </p>
        </div>

        <div class="space-y-12 py-10">
            <div class="card bg-base-100">
                <div class="card-body">
                    <div class="flex flex-col w-full items-center md:flex-row md:justify-between">
                        <div class="flex items-center pb-8 md:flex-col md:justify-center md:w-1/2 md:pb-0">
                            <img class="w-1/2 md:w-3/4"
                                 src="{% static 'img/booking_re_gw4j.svg' %}"
                                 alt="Events">
                            <div class="ml-3 md:text-center md:ml-0 md:pt-8 md:w-1/2">
                                <h2 class="card-title md:justify-center text-primary font-serif">Events</h2>
                                <p class="pt-1">The following events are scheduled for the coming days</p>
                            </div>
                        </div>

                        <div class="md:w-1/2">
                            {% if events %}
                                <ul class="timeline timeline-snap-icon max-md:timeline-compact timeline-vertical">
                                    {% for event in events %}
                                        <li>
                                            {% if not forloop.counter == 1 %}<hr />{% endif %}
                                            <div class="timeline-middle">
                                                <svg xmlns="http://www.w3.org/2000/svg"
                                                     viewBox="0 0 20 20"
                                                     fill="currentColor"
                                                     class="h-5 w-5">
                                                    <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.857-9.809a.75.75 0 00-1.214-.882l-3.483 4.79-1.88-1.88a.75.75 0 10-1.06 1.061l2.5 2.5a.75.75 0 001.137-.089l4-5.5z" clip-rule="evenodd">
                                                    </path>
                                                </svg>
                                            </div>
                                            <div class="{% if forloop.counter0|divisibleby:2 %}timeline-start md:text-end{% else %}timeline-end{% endif %} mb-10">
                                                <time class="italic">
                                                {{ event.start|date:"M j, f a" }}</time>
                                                <div class="text-lg font-bold">{{ event.title }}</div>
                                                <p class="badge badge-secondary">{{ event.church }}</p>
                                                {% if event.live_stream %}
                                                    <div class="pt-1">
                                                        <a href="{% url 'streams:streams-list' %}"
                                                           class="btn btn-xs btn-outline btn-primary">
                                                            <i class="fa-solid fa-circle mr-1"></i>Live
                                                        </a>
                                                    </div>
                                                {% endif %}
                                            </div>
                                            <hr />
                                        </li>
                                    {% endfor %}
                                </ul>
                            {% else %}
                                <div class="text-center text-lg">
                                    <p>Looks like there are no events planned at this moment.</p>
                                    <p>Check back later.</p>
                                </div>
                            {% endif %}
                        </div>
                    </div>
                    <div class="flex justify-center pt-8">
                        <a href="{% url 'schedules:events-list' %}" class="btn btn-primary">
                            <i class="fa-solid fa-calendar mr-2"></i>
                            All Events
                        </a>
                    </div>
                </div>
            </div>
            {# Live stream section #}
            <div class="flex flex-col-reverse items-center justify-around md:flex-row">
                <div class="card bg-base-100 w-1/2 md:w-1/3">
                    <div class="card-body">
                        <h2 class="card-title text-primary justify-center font-serif">Live Stream</h2>
                        <p class="pt-1 text-center">
                            If you are not able to assist in person, We also livestream some of
                            our
                            events
                        </p>
                        <div class="my-4 text-center">
                            <a href="{% url 'streams:streams-list' %}" class="btn btn-primary">
                                <i class="fa-solid fa-circle mr-2"></i>
                                Live
                            </a>
                        </div>
                    </div>
                </div>
                <img class="w-1/2 md:w-1/3"
                     src="{% static 'img/video_streaming_re_v3qg.svg' %}"
                     alt="Live">
            </div>
            {# Sermons section #}
            <div class="card bg-base-100">
                <div class="card-body flex-col items-center md:flex-row justify-around">
                    <div class="flex flex-col justify-center items-center w-full md:w-1/2 px-8">
                        <img class="w-3/4"
                             src="{% static 'img/media_player_re_rdd2.svg' %}"
                             alt="Live">
                        <div class="flex flex-col justify-center items-center pt-8">
                            <h2 class="card-title text-primary font-serif">Sermons</h2>
                            <p class="pt-1 text-center">Browse through our historical sermons that we have recorded</p>
                            <div class="my-4">
                                <a href="{% url 'sermons:sermons-list' %}" class="btn btn-primary">
                                    <i class="fa-solid fa-circle mr-2"></i>
                                    Sermons
                                </a>
                            </div>
                        </div>
                    </div>

                    <div class="flex flex-col w-full md:w-1/2 md:pl-8">
                        {% for sermon in sermons %}
                            <a href="{% url 'sermons:sermons-detail' pk=sermon.pk church=sermon.event.church %}"
                               class="flex flex-col card bg-secondary text-white shadow overflow-hidden w-full my-3 hover:bg-secondary-focus">
                                <div class="card-body px-4 py-2 gap-0">
                                    <h3 class="font-bold pb-2 truncate">{{ sermon.title }}</h3>
                                    <p class="text-sm">{{ sermon.event.start.date|date:"M j, Y" }}</p>
                                    <div class="divider my-1"></div>
                                    <div class="flex flex-row items-center justify-start">
                                        {% for speaker in sermon.speakers.all %}
                                            <p class="text-sm mr-2 grow-0">
                                                {% if forloop.first %}<i class="fa-solid fa-microphone mr-1"></i>{% endif %}
                                                {{ speaker.name }}
                                                {% if not forloop.last %},{% endif %}
                                            </p>
                                        {% endfor %}
                                    </div>
                                </div>
                            </a>
                        {% endfor %}
                    </div>
                </div>
            </div>
            {# Contact form #}
            <div class="flex flex-col items-center md:justify-around md:flex-row">
                <img class="w-3/4 md:w-1/2"
                     src="{% static 'img/personal_text_re_vqj3.svg' %}"
                     alt="Person looking at a messages">
                {% include "contactus/contact-form.html" %}

            </div>
        </div>
    </div>
{% endblock %}