church_site/urls.py
from allauth.account.views import confirm_email, email_verification_sent
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from rest_framework import routers

# from telegram.api.controllers import LiveSubscriptionViewSet

router = routers.DefaultRouter()
# router.register(r'subscription/live', LiveSubscriptionViewSet)
# router.register(r'streams', StreamsViewSet)

urlpatterns = [
    path("", include("core.urls")),
    path(settings.ADMIN_URL, admin.site.urls),
    path("accounts/", include("allauth.urls")),
    path("api/v1/", include(router.urls)),
    path("api/v1/streams/", include("streams.api.urls")),
    # path('api/v1/telegram/', include('telegram.api_urls')),
    path("api-auth/", include("rest_framework.urls", namespace="rest_framework")),
    path(
        "dj-rest-auth/registration/account-confirm-email/<str:key>/",
        confirm_email,
        name="account_email_verification_sent",
    ),
    path(
        "dj-rest-auth/registration/account-email-verification-sent/",
        email_verification_sent,
        name="account_email_verification_sent",
    ),
    path("dj-rest-auth/", include("dj_rest_auth.urls")),
    path("dj-rest-auth/registration/", include("dj_rest_auth.registration.urls")),
    path("users/", include("accounts.urls")),
    path("bulletin/", include("bulletin.urls")),
    path("churches/", include("churches.urls")),
    path("speakers/", include("speakers.urls")),
    path("schedules/", include("schedules.urls")),
    path("sermons/", include("sermons.urls")),
    path("streams/", include("streams.urls")),
    path("contactus/", include("contactus.urls")),
    path("forms/", include("forms.urls")),
    path("robots.txt", TemplateView.as_view(template_name="robots.txt", content_type="text/plain")),
    path("sitemap.xml", TemplateView.as_view(template_name="sitemap.xml", content_type="text/xml")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contactus/urls.py
from django.urls import path

from .views import AdminContactMessageListView, AdminContactMessageDetailView, AdminReadMessage, AdminContactMessageDeleteView

app_name = 'contactus'

urlpatterns = [
    path('manage/messages/', AdminContactMessageListView.as_view(), name='admin-messages'),
    path('manage/messages/<int:pk>/', AdminContactMessageDetailView.as_view(), name='admin-message-detail'),
    path('manage/messages/<int:pk>/read/', AdminReadMessage.as_view(), name='admin-read-message'),
    path('manage/messages/<int:pk>/delete/', AdminContactMessageDeleteView.as_view(), name='admin-delete-message'),
]

core/urls.py
from django.urls import path

from core.views import HomeView
from core.views.pages import set_timezone

app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('set_timezone/', set_timezone, name='set_timezone')
]

contactus/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone

from contactus.querysets import ContactMessageQuerySet


class ContactMessage(models.Model):
    page_title = models.CharField(max_length=50)
    name = models.CharField(max_length=50, null=True, blank=True)
    email = models.EmailField(blank=True, null=True)
    phone_number = models.CharField(max_length=15, blank=True, null=True)
    message = models.TextField()
    message_date = models.DateTimeField(auto_now_add=True)
    read = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    deleted_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=True, blank=True)

    objects = ContactMessageQuerySet.as_manager()

    class Meta:
        ordering = ['message_date']

    def __str__(self):
        return timezone.localtime(self.message_date).strftime('%Y-%m-%d, %H:%M:%I %p')

contactus/forms.py
from datetime import datetime, timedelta
from django.forms import HiddenInput, DateTimeField
from django.utils import timezone

from contactus.models import ContactMessage
from core.forms import CoreModelForm


class ContactUsForm(CoreModelForm):
    form_no = DateTimeField(widget=HiddenInput(), initial=timezone.now)

    class Meta:
        model = ContactMessage
        fields = ('page_title', 'name', 'email', 'phone_number', 'message')
        widgets = {
            'page_title': HiddenInput(),
        }

    def save(self, commit=False):
        form_no_plus_five = datetime.strptime(self.data['form_no'],
                                              '%Y-%m-%d %H:%M:%S.%f') + timedelta(seconds=5)
        if self.cleaned_data['form_no'] is None or form_no_plus_five > datetime.now():
            return super().save(commit=False)
        return super().save(commit=True)

contactus/views.py
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.views import View

from core.views.base import AdminListView, BaseDetailView

from contactus.models import ContactMessage


class AdminContactMessageListView(PermissionRequiredMixin, AdminListView):
    permission_required = 'contactus.view_contactmessage'
    template_name = 'contactus/admin-contact-messages.html'
    model = ContactMessage
    context_object_name = 'contact_messages'
    queryset = ContactMessage.objects.all_existing()
    ordering = ['-message_date']
    page_title = 'Contact Messages - Admin'
    current_page = 'admin_messages'


class AdminContactMessageDetailView(PermissionRequiredMixin, BaseDetailView):
    permission_required = 'contactus.view_contactmessage'
    template_name = 'contactus/admin-message-detail.html'
    model = ContactMessage
    context_object_name = 'contact_msg'
    # queryset = ContactMessage.objects.all_existing
    page_title = 'Contact Message - Admin'
    current_page = 'admin_messages'


class AdminContactMessageDeleteView(PermissionRequiredMixin, View):
    permission_required = 'contactus.delete_contactmessage'

    def post(self, request, pk=None):
        msg = ContactMessage.objects.filter(id=pk).first()
        if msg:
            msg.deleted = True
            msg.deleted_by = request.user
            msg.save()
        return redirect('contactus:admin-messages')


class AdminReadMessage(PermissionRequiredMixin, View):
    permission_required = 'contactus.change_contactmessage'

    def get(self, request, pk=None):
        msg = ContactMessage.objects.filter(id=pk).first()
        if msg:
            msg.read = not msg.read
            msg.save()
        return redirect('contactus:admin-message-detail', pk=pk)

templates/contactus/admin-contact-messages.html
{% extends 'admin-list-layout.html' %}

{% block table_head %}
  <tr>
    <th>Name</th>
    <th>Message</th>
    <th>Date & Time</th>
    <th>Read</th>
    <th>Actions</th>
  </tr>
{% endblock %}

{% block table_body %}
  {% for message in contact_messages %}
    <tr>
      <td class="align-middle">{% if message.name %}{{ message.name }}{% endif %}</td>
      <td class="align-middle truncate">{{ message.message|truncatechars:"50" }}</td>
      <td class="align-middle">{{ message.message_date }}</td>
      <td class="align-middle">
        {% if message.read %}
          <i class="fa-solid fa-check"></i>
        {% endif %}
      </td>
      <td class="align-middle">
        <a class="btn btn-sm btn-primary" href="{% url 'contactus:admin-message-detail' pk=message.id %}"><i
            class="fa-solid fa-clipboard"></i>
        </a>
        {#                <button class="btn btn-sm btn-error">#}
        {#                    <i class="fa-solid fa-trash-alt"></i>#}
        {#                </button>#}
      </td>
    </tr>
  {% endfor %}
{% endblock %}

templates/contactus/admin-message-detail.html
{% extends '_layout.html' %}

{% block content %}
  {{ block.super }}

  <div class="px-3 py-4">

    <a href="{% url 'contactus:admin-messages' %}" class="btn btn-outline my-4">
      <i class="fa-solid fa-arrow-left mr-2"></i> Back
    </a>

    <div class="card bg-base-100">
      <div class="card-body">
        <h1 class="card-title text-2xl">Message</h1>
        <hr>
        <h5 class="font-semibold">Date & Time</h5>
        <p>{{ contact_msg.message_date }}</p>

        <h5 class="pt-3 font-semibold">Sent from page</h5>
        <p>{{ contact_msg.page_title }}</p>

        {#                {% if contact_msg.name %}#}
        <h5 class="pt-3 font-semibold">Name</h5>
        <p>{{ contact_msg.name }}</p>
        {#                {% endif %}#}

        {% if contact_msg.email %}
          <h5 class="pt-3 font-semibold">Email</h5>
          <p>{{ contact_msg.email }}</p>
        {% endif %}

        {% if contact_msg.phone_number %}
          <h5 class="pt-3 font-semibold">Phone Number</h5>
          <p>{{ contact_msg.phone_number }}</p>
        {% endif %}

        <h5 class="pt-3 font-semibold">Message</h5>
        <p>{{ contact_msg.message|linebreaksbr }}</p>

        <div class="text-center pt-3">
          <a class="btn btn-primary mr-2"
             href="{% url 'contactus:admin-read-message' pk=contact_msg.id %}">
            {% if contact_msg.read %}
              Mark Unread
            {% else %}
              Mark Read
            {% endif %}
          </a>
          <label for="delete-modal" class="btn btn-error"><i class="fa-solid fa-trash mr-2"></i>Delete</label>
        </div>
      </div>
    </div>
  </div>

  <input type="checkbox" id="delete-modal" class="modal-toggle" />
  <div class="modal modal-bottom sm:modal-middle">
    <div class="modal-box bg-base-100">
      <h3 class="font-bold text-lg">Delete {{ contact_msg.message_date }}</h3>
      <p class="py-4">Are you sure you want to delete {{ contact_msg.message_date }}?</p>
      <div class="modal-action">
        <label for="delete-modal" class="btn">Cancel</label>
        <form method="post" action="{% url 'contactus:admin-delete-message' pk=contact_msg.id %}">
          {% csrf_token %}
          <button type="submit" class="btn btn-error">Delete</button>
        </form>
      </div>
    </div>
  </div>
{% endblock %}

templates/contactus/contact-form.html
<div class="card glass">
  <div class="card-body">
    <h2 class="text-2xl text-center text-primary pb-4"><i class="fa-solid fa-envelope"></i> Contact Us</h2>
    <form method="post">
      {% csrf_token %}

      {{ form.page_title }}
      {{ form.form_no }}

      <label for="id_name" class="label">
        <span class="label-text">{{ form.name.label }}</span>
      </label>
      {{ form.name }}

      <label for="id_email" class="label">
        <span class="label-text">{{ form.email.label }}</span>
      </label>
      {{ form.email }}

      <label for="id_phone_number" class="label">
        <span class="label-text">{{ form.phone_number.label }}</span>
      </label>
      {{ form.phone_number }}

      <label for="id_message" class="label">
        <span class="label-text">{{ form.message.label }}</span>
      </label>
      {{ form.message }}

      <div class="flex justify-center pt-2">
        <button type="submit" class="btn btn-primary"><i class="fa-solid fa-paper-plane mr-2"></i> Send</button>
      </div>
    </form>
  </div>
</div>